name: Issue Notification

on:
  issue_comment:
    types: [created]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract issue information
        id: extract_issue_info
        run: |
          ISSUE_NUMBER=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)
          ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          ISSUE_BODY=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
          POST_LINK=$(echo "$ISSUE_BODY" | grep -oP '(?<=\[).*?(?=\])')
          COMMENT_BODY=$(jq -r '.comment.body' $GITHUB_EVENT_PATH)
          COMMENT_USER=$(jq -r '.comment.user.login' $GITHUB_EVENT_PATH)

          echo "::set-output name=issue_number::$ISSUE_NUMBER"
          echo "::set-output name=issue_title::$ISSUE_TITLE"
          echo "::set-output name=post_link::$POST_LINK"
          echo "::set-output name=comment_body::$COMMENT_BODY"
          echo "::set-output name=comment_user::$COMMENT_USER"

      - name: Send opened issues notifications
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"embeds": [{"title": "이슈(댓글) 등록 알림", "description": "원문: [${{ steps.extract_issue_info.outputs.issue_title }}](${{ steps.extract_issue_info.outputs.post_link }})\n작성자: `${{ steps.extract_issue_info.outputs.comment_user }}`\n내용: `${{ steps.extract_issue_info.outputs.comment_body }}`"}]}' \
          '${{ secrets.DISCORD_WEBHOOK }}'
